---

- name: Install rastream_extra_packages
  openbsd_pkg:
    name: "{{ rastream_extra_packages }}"
    state: present

- name: Install rastream_package
  openbsd_pkg:
    name: "{{ rastream_package }}"
    state: present
  when:
    - rastream_package is defined
    - rastream_package | length > 0

- name: Create /etc/rc.d/rastream
  template:
    src: OpenBSD.rc.j2
    dest: /etc/rc.d/rastream
    mode: '0755'
    validate: sh -n %s

- name: Enable rastream_service
  service:
    name: "{{ rastream_service }}"
    arguments: "{{ rastream_flags }}"
    enabled: yes
  notify:
    - Restart rastream_service
