---

- name: Install rastream_extra_packages
  pkgng:
    name: "{{ rastream_extra_packages }}"
    state: present

- name: Install rastream_package
  pkgng:
    name: "{{ rastream_package }}"
    state: present
  when:
    - rastream_package is defined
    - rastream_package | length > 0

- name: Create rc.d/rastream
  template:
    src: FreeBSD.rc.j2
    dest: /usr/local/etc/rc.d/rastream
    mode: '0755'
    validate: sh -n %s
  notify:
    - Restart rastream_service

- name: Enable rastream_service
  service:
    name: "{{ rastream_service }}"
    enabled: yes

- name: "Create /etc/rc.conf.d/{{ rastream_service }}"
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ rastream_service }}"
    mode: 0644
    validate: sh -n %s
  notify:
    - Restart rastream_service
