---

- name: Install rastream_extra_packages
  yum:
    name: "{{ rastream_extra_packages }}"
    state: present

- name: Install rastream_package
  yum:
    name: "{{ rastream_package }}"
    state: present

- name: Create symlink to /usr/lib64/sasl2
  # XXX workaround hard-coded path to /usr/lib/sasl2
  file:
    src: /usr/lib64/sasl2
    dest: /usr/lib/sasl2
    state: link
  when:
    - ansible_userspace_bits == "64"

- name: "Create /etc/sysconfig/{{ rastream_service }}"
  template:
    src: RedHat.sysconfig.j2
    dest: "/etc/sysconfig/{{ rastream_service }}"
    mode: 0644
    # keep the original copy in case you need the defaults in it
    backup: yes
    validate: sh -n %s
  notify:
    - Restart rastream_service

- name: Create systemd unit file
  template:
    src: systemd.unit.j2
    dest: "/lib/systemd/system/{{ rastream_service }}.service"
    mode: '0644'
  notify:
    - Reload systemd in rastream
    - Restart rastream_service

- name: Enable rastream_service
  service:
    name: "{{ rastream_service }}"
    enabled: yes
